#!/usr/bin/env bash
# StarNion Docker Setup
# Initializes the full Docker Compose stack: generates secrets, writes .env,
# builds images, and starts all services.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$ROOT_DIR/.env"
COMPOSE_FILE="$ROOT_DIR/docker-compose.yml"

# ── Colors ────────────────────────────────────────────────────────────────────
GOLD='\033[0;33m'
GREEN='\033[0;32m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}  ℹ  $*${NC}"; }
ok()    { echo -e "${GREEN}  ✓  $*${NC}"; }
fail()  { echo -e "${RED}  ✗  $*${NC}" >&2; exit 1; }
banner(){ echo -e "${GOLD}$*${NC}"; }

# ── Checks ────────────────────────────────────────────────────────────────────
require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    fail "Required command not found: $1"
  fi
}

require_cmd docker
if ! docker compose version >/dev/null 2>&1; then
  fail "Docker Compose plugin not available. Install: https://docs.docker.com/compose/install/"
fi

# ── Banner ────────────────────────────────────────────────────────────────────
echo
banner "  ╔══════════════════════════════════════╗"
banner "  ║     ✦  StarNion  Docker  Setup  ✦    ║"
banner "  ╚══════════════════════════════════════╝"
echo

# ── Secret generation ─────────────────────────────────────────────────────────
gen_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    python3 -c "import secrets; print(secrets.token_hex(32))"
  fi
}

# ── Load existing .env or build from starnion config ──────────────────────────
if [[ -f "$ENV_FILE" ]]; then
  info "기존 .env 파일이 존재합니다. 값을 유지합니다."
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE"; set +a
elif command -v starnion >/dev/null 2>&1 && starnion doctor 2>/dev/null | grep -q "✓.*Config"; then
  info "starnion config 발견. docker/.env를 생성합니다..."
  starnion docker setup --env-only 2>/dev/null || true
  if [[ -f "$ENV_FILE" ]]; then
    set -a; source "$ENV_FILE"; set +a
  fi
fi

# ── Ensure required secrets ───────────────────────────────────────────────────
echo
info "[1/5] 시크릿 생성 중..."
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(gen_secret)}"
MINIO_SECRET_KEY="${MINIO_SECRET_KEY:-$(gen_secret)}"
JWT_SECRET="${JWT_SECRET:-$(gen_secret)}"
AUTH_SECRET="${AUTH_SECRET:-$(gen_secret)}"

# ── Set defaults ──────────────────────────────────────────────────────────────
POSTGRES_DB="${POSTGRES_DB:-starnion}"
POSTGRES_USER="${POSTGRES_USER:-starnion}"
POSTGRES_PORT="${POSTGRES_PORT:-5432}"
MINIO_ACCESS_KEY="${MINIO_ACCESS_KEY:-starnion}"
MINIO_BUCKET="${MINIO_BUCKET:-starnion-files}"
MINIO_PORT="${MINIO_PORT:-9000}"
MINIO_CONSOLE_PORT="${MINIO_CONSOLE_PORT:-9001}"
MINIO_PUBLIC_URL="${MINIO_PUBLIC_URL:-http://localhost:9000}"
GATEWAY_PORT="${GATEWAY_PORT:-8080}"
GATEWAY_PUBLIC_URL="${GATEWAY_PUBLIC_URL:-http://localhost:8080}"
GRPC_PORT="${GRPC_PORT:-50051}"
UI_PORT="${UI_PORT:-3000}"
NEXTAUTH_URL="${NEXTAUTH_URL:-http://localhost:3000}"

# ── Write .env ────────────────────────────────────────────────────────────────
info "[2/5] docker/.env 작성 중..."
cat > "$ENV_FILE" <<EOF
# StarNion Docker Environment — auto-generated by setup.sh
# $(date -u '+%Y-%m-%dT%H:%M:%SZ')

# Secrets
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
JWT_SECRET=${JWT_SECRET}
AUTH_SECRET=${AUTH_SECRET}

# PostgreSQL
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PORT=${POSTGRES_PORT}

# MinIO
MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_BUCKET=${MINIO_BUCKET}
MINIO_PORT=${MINIO_PORT}
MINIO_CONSOLE_PORT=${MINIO_CONSOLE_PORT}
MINIO_PUBLIC_URL=${MINIO_PUBLIC_URL}

# Gateway
GATEWAY_PORT=${GATEWAY_PORT}
GATEWAY_PUBLIC_URL=${GATEWAY_PUBLIC_URL}
GRPC_PORT=${GRPC_PORT}

# UI
UI_PORT=${UI_PORT}
NEXTAUTH_URL=${NEXTAUTH_URL}
EOF
chmod 600 "$ENV_FILE"
ok "docker/.env 작성 완료"

# ── Build images ──────────────────────────────────────────────────────────────
echo
info "[3/5] Docker 이미지 빌드 중..."
docker compose -f "$COMPOSE_FILE" build
ok "이미지 빌드 완료"

# ── Start infra first ─────────────────────────────────────────────────────────
echo
info "[4/5] 인프라 서비스 시작 중 (postgres, minio)..."
docker compose -f "$COMPOSE_FILE" up -d postgres minio

# Wait for postgres
echo -n "  PostgreSQL 준비 대기 중"
for i in $(seq 1 30); do
  if docker compose -f "$COMPOSE_FILE" exec -T postgres pg_isready -U "$POSTGRES_USER" >/dev/null 2>&1; then
    echo; ok "PostgreSQL 준비됨"
    break
  fi
  echo -n "."
  sleep 2
  if [[ $i -eq 30 ]]; then
    echo; fail "PostgreSQL 시작 시간 초과"
  fi
done

# Wait for minio
echo -n "  MinIO 준비 대기 중"
for i in $(seq 1 30); do
  if curl -sf "http://localhost:${MINIO_PORT}/minio/health/live" >/dev/null 2>&1; then
    echo; ok "MinIO 준비됨"
    break
  fi
  echo -n "."
  sleep 2
  if [[ $i -eq 30 ]]; then
    echo; fail "MinIO 시작 시간 초과"
  fi
done

# ── Start all services ────────────────────────────────────────────────────────
echo
info "[5/5] 전체 서비스 시작 중..."
docker compose -f "$COMPOSE_FILE" up -d
ok "모든 서비스 시작 완료"

# ── Done ──────────────────────────────────────────────────────────────────────
echo
banner "  ══════════════════════════════════════════"
banner "  ✦  StarNion Docker 설정 완료  ✦"
banner "  ══════════════════════════════════════════"
echo
echo -e "  서비스 URL:"
echo -e "    UI:      ${GOLD}http://localhost:${UI_PORT}${NC}"
echo -e "    Gateway: ${GOLD}http://localhost:${GATEWAY_PORT}${NC}"
echo -e "    MinIO:   ${GOLD}http://localhost:${MINIO_CONSOLE_PORT}${NC}  (콘솔)"
echo
echo -e "  관리 명령어:"
echo -e "    로그 확인:  ${CYAN}starnion docker logs${NC}"
echo -e "    상태 확인:  ${CYAN}starnion docker ps${NC}"
echo -e "    서비스 중지: ${CYAN}starnion docker down${NC}"
echo
