package cli

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// StarPionConfig is the single source of truth for all service configuration.
// Stored at ~/.config/starpion/config.yaml (permissions 0600).
type StarPionConfig struct {
	Version  string         `yaml:"version"`
	Database DatabaseConfig `yaml:"database"`
	Admin    AdminConfig    `yaml:"admin"`
	MinIO    MinIOConfig    `yaml:"minio"`
	Gateway  GatewayConfig  `yaml:"gateway"`
	UI       UIConfig       `yaml:"ui"`
	Auth     AuthConfig     `yaml:"auth"`
}

type DatabaseConfig struct {
	Host     string `yaml:"host"`
	Port     int    `yaml:"port"`
	Name     string `yaml:"name"`
	User     string `yaml:"user"`
	Password string `yaml:"password"`
	SSLMode  string `yaml:"ssl_mode"`
}

type AdminConfig struct {
	Email string `yaml:"email"`
}

type MinIOConfig struct {
	Endpoint  string `yaml:"endpoint"`
	AccessKey string `yaml:"access_key"`
	SecretKey string `yaml:"secret_key"`
	Bucket    string `yaml:"bucket"`
	PublicURL string `yaml:"public_url"`
	UseSSL    bool   `yaml:"use_ssl"`
}

type GatewayConfig struct {
	URL      string `yaml:"url"`
	Port     int    `yaml:"port"`
	GRPCPort int    `yaml:"grpc_port"`
}

type UIConfig struct {
	Port int `yaml:"port"`
}

type AuthConfig struct {
	JWTSecret  string `yaml:"jwt_secret"`
	AuthSecret string `yaml:"auth_secret"`
}

// DefaultConfig returns a config with sensible defaults.
func DefaultConfig() StarPionConfig {
	return StarPionConfig{
		Version: "1.0.0",
		Database: DatabaseConfig{
			Host:    "localhost",
			Port:    5432,
			Name:    "starpion",
			User:    "postgres",
			SSLMode: "disable",
		},
		MinIO: MinIOConfig{
			Endpoint:  "localhost:9000",
			Bucket:    "starpion-files",
			PublicURL: "http://localhost:9000",
			UseSSL:    false,
		},
		Gateway: GatewayConfig{
			URL:      "http://localhost:8080",
			Port:     8080,
			GRPCPort: 50051,
		},
		UI: UIConfig{Port: 3000},
	}
}

// ConfigDir returns ~/.config/starpion.
func ConfigDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "starpion")
}

// ConfigPath returns the full path to config.yaml.
func ConfigPath() string {
	return filepath.Join(ConfigDir(), "config.yaml")
}

// ConfigExists reports whether the config file has been created.
func ConfigExists() bool {
	_, err := os.Stat(ConfigPath())
	return err == nil
}

// LoadConfig reads and parses config.yaml. Returns DefaultConfig if not found.
func LoadConfig() (StarPionConfig, error) {
	cfg := DefaultConfig()
	data, err := os.ReadFile(ConfigPath())
	if os.IsNotExist(err) {
		return cfg, nil
	}
	if err != nil {
		return cfg, fmt.Errorf("read config: %w", err)
	}
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return cfg, fmt.Errorf("parse config: %w", err)
	}
	return cfg, nil
}

// SaveConfig writes cfg to ~/.config/starpion/config.yaml with mode 0600.
func SaveConfig(cfg StarPionConfig) error {
	dir := ConfigDir()
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	if err := os.WriteFile(ConfigPath(), data, 0o600); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}

// DSN builds a postgres DSN from DatabaseConfig.
func (d DatabaseConfig) DSN() string {
	return fmt.Sprintf("host=%s port=%d dbname=%s user=%s password=%s sslmode=%s",
		d.Host, d.Port, d.Name, d.User, d.Password, d.SSLMode)
}

// DatabaseURL returns the postgresql:// URL form.
func (d DatabaseConfig) DatabaseURL() string {
	return fmt.Sprintf("postgresql://%s:%s@%s:%d/%s?sslmode=%s",
		d.User, d.Password, d.Host, d.Port, d.Name, d.SSLMode)
}

// randomSecret generates a cryptographically random hex string of `bytes` bytes.
func randomSecret(bytes int) string {
	b := make([]byte, bytes)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

// EnsureSecrets auto-generates JWT and Auth secrets if they are empty.
func EnsureSecrets(cfg *StarPionConfig) bool {
	changed := false
	if cfg.Auth.JWTSecret == "" {
		cfg.Auth.JWTSecret = randomSecret(32)
		changed = true
	}
	if cfg.Auth.AuthSecret == "" {
		cfg.Auth.AuthSecret = randomSecret(32)
		changed = true
	}
	return changed
}

// WriteDockerEnv generates docker/.env for Docker Compose from the config.
// This is the single source of truth that docker-compose.yml reads via ${VAR} interpolation.
func WriteDockerEnv(cfg StarPionConfig, dockerDir string) error {
	db := cfg.Database
	gw := cfg.Gateway

	content := fmt.Sprintf(`# StarPion Docker Environment — auto-generated by starpion docker setup
# Edit ~/.config/starpion/config.yaml and re-run 'starpion docker setup' to regenerate.

# Secrets
POSTGRES_PASSWORD=%s
MINIO_SECRET_KEY=%s
JWT_SECRET=%s
AUTH_SECRET=%s

# PostgreSQL
POSTGRES_DB=%s
POSTGRES_USER=%s
POSTGRES_PORT=%d

# MinIO
MINIO_ACCESS_KEY=%s
MINIO_BUCKET=%s
MINIO_PORT=9000
MINIO_CONSOLE_PORT=9001
MINIO_PUBLIC_URL=%s

# Gateway
GATEWAY_PORT=%d
GATEWAY_PUBLIC_URL=%s
GRPC_PORT=%d

# UI
UI_PORT=%d
NEXTAUTH_URL=http://localhost:%d
`,
		db.Password,
		cfg.MinIO.SecretKey,
		cfg.Auth.JWTSecret,
		cfg.Auth.AuthSecret,
		db.Name,
		db.User,
		db.Port,
		cfg.MinIO.AccessKey,
		cfg.MinIO.Bucket,
		cfg.MinIO.PublicURL,
		gw.Port,
		gw.URL,
		gw.GRPCPort,
		cfg.UI.Port,
		cfg.UI.Port,
	)

	path := filepath.Join(dockerDir, ".env")
	return os.WriteFile(path, []byte(content), 0o600)
}

// WriteEnvFiles generates per-service .env files from the config.
// Each service only sees the variables it needs.
func WriteEnvFiles(cfg StarPionConfig, projectRoot string) error {
	db := cfg.Database

	// ── gateway/.env ─────────────────────────────────────────────────────────
	gatewayEnv := fmt.Sprintf(`# Auto-generated by starpion setup — do not edit manually.
DATABASE_URL=%s
JWT_SECRET=%s
GRPC_PORT=%d
GRPC_AGENT_HOST=localhost:%d
GOOGLE_REDIRECT_URI=%s/auth/google/callback
MINIO_ENDPOINT=%s
MINIO_ACCESS_KEY=%s
MINIO_SECRET_KEY=%s
MINIO_BUCKET=%s
MINIO_PUBLIC_URL=%s
`,
		db.DatabaseURL(),
		cfg.Auth.JWTSecret,
		cfg.Gateway.GRPCPort,
		cfg.Gateway.GRPCPort,
		cfg.Gateway.URL,
		cfg.MinIO.Endpoint,
		cfg.MinIO.AccessKey,
		cfg.MinIO.SecretKey,
		cfg.MinIO.Bucket,
		cfg.MinIO.PublicURL,
	)

	// ── agent/.env ───────────────────────────────────────────────────────────
	agentEnv := fmt.Sprintf(`# Auto-generated by starpion setup — do not edit manually.
DATABASE_URL=%s
GRPC_PORT=%d
`,
		db.DatabaseURL(),
		cfg.Gateway.GRPCPort,
	)

	// ── ui/.env ──────────────────────────────────────────────────────────────
	uiEnv := fmt.Sprintf(`# Auto-generated by starpion setup — do not edit manually.
AUTH_SECRET=%s
GATEWAY_WS_URL=%s
GATEWAY_API_URL=%s
API_URL=%s
JWT_SECRET=%s
`,
		cfg.Auth.AuthSecret,
		strings.Replace(cfg.Gateway.URL, "http://", "ws://", 1),
		cfg.Gateway.URL,
		cfg.Gateway.URL,
		cfg.Auth.JWTSecret,
	)

	files := map[string]string{
		filepath.Join(projectRoot, "gateway", ".env"): gatewayEnv,
		filepath.Join(projectRoot, "agent", ".env"):   agentEnv,
		filepath.Join(projectRoot, "ui", ".env"):      uiEnv,
	}
	for path, content := range files {
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}
