-- Migration 026: Add user_audios table
-- Tracks all audio files: recorded/uploaded by user, TTS generated by agent
-- Sources: web, telegram, webchat

CREATE TABLE IF NOT EXISTS user_audios (
    id         BIGSERIAL   PRIMARY KEY,
    user_id    TEXT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    url        TEXT        NOT NULL,
    name       TEXT        NOT NULL DEFAULT 'audio.wav',
    mime       TEXT        NOT NULL DEFAULT 'audio/wav',
    size       BIGINT      NOT NULL DEFAULT 0,
    duration   INTEGER     NOT NULL DEFAULT 0,  -- seconds (best-effort)
    source     TEXT        NOT NULL DEFAULT 'web',     -- 'web', 'telegram', 'webchat'
    type       TEXT        NOT NULL DEFAULT 'uploaded', -- 'uploaded', 'recorded', 'generated'
    transcript TEXT,   -- STT result
    prompt     TEXT,   -- TTS source text
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_audios_user_id    ON user_audios(user_id);
CREATE INDEX IF NOT EXISTS idx_user_audios_created_at ON user_audios(created_at DESC);
